# optional: provide config file here:
#configfile: "config.yml"
'''
from snakemake.utils import min_version
min_version("5.3.0")

# set sample ids for whole workflow:
#SAMPLES = ["SRR935090", "SRR935091", "SRR935092"]


# define an empty 'samples' dictionary
fq_paths = []
sample_id = []
mate = []

# read the sample list file and populate the dictionary
#with open("samples.tsv", "r") as fhin:
# populate from config-yml:
with open(config["sample_list"], "r") as fhin:
    for line in fhin:
        # strip the newline character from the end of the line
        # then split by tab character to get the sample id and url
        query="_R1_001_50k_fastq.gz"
        fq_path = line.strip()
        if query in fq_path:
            fq_paths.append(fq_path) 
            mate.append("R1")
        else:
            fq_paths.append(fq_path) 
            mate.append("R2")
print(fq_paths)
print(sample_id)
print(mate)
'''


rule fastqc:
    """
    Run FastQC on a FASTQ file.
    """
    output:
        '{sample_id}_fastq.fastp.gz'
        #'0246_2_TP04_026_FC_MOD_1TR1_SL1_S26_L002_R1_001_50k_fastq.fastp.gz'
    input:
        '{sample_id}.gz'
        #'0246_2_TP04_026_FC_MOD_1TR1_SL1_S26_L002_R1_001_50k_fastq.gz'
    log:
        # 2>$1 fwd both
        "logs/fastp/{sample_id}.log"
    shell:
        """
        time fastp -i {input[0]} {output[0]} 2>$1 {log}
        """

#    input:
#        #"home/AD/hermi/sm_tutorial/BYOC/myData/0246_2_TP04_026_FC_MOD_1TR1_SL1_S26_L002_R1_001_50k_fastq.gz",
#        #"home/AD/hermi/sm_tutorial/BYOC/myData/0246_2_TP04_026_FC_MOD_1TR1_SL1_S26_L002_R2_001_50k_fastq.gz"
# .snakemake/log/2024-05-27T125611.315731.snakemake.log


