software-deployment-method: "conda"
local-cores: "1" # number of cores used on the headnode
jobs: "25" # maximum number of jobs to be submitted in parallel
printshellcmds: "True"
conda-frontend: "mamba"
verbose: "True"
restart-times: 3
jobscript: "slurm-jobscript.sh"
cluster-generic-sidecar: "slurm-sidecar.py"
cluster-generic-cancel-cmd: "scancel"
cluster-generic-submit-cmd: "slurm-submit.py"
cluster-generic-status-cmd: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60
# Example resource configuration
default-resources:
    - tmpdir="/scratch"
#   - runtime=100
#   - mem_mb=6000
#   - disk_mb=1000000
# # set-threads: map rule names to threads
# set-threads:
#   - single_core_rule=1
#   - multi_core_rule=10
# # set-resources: map rule names to resources in general
# set-resources:
#   - high_memory_rule:mem_mb=12000
#   - long_running_rule:runtime=1200
